//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndruhaBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezume()
        {
            this.UserRezume = new HashSet<UserRezume>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string job { get; set; }
        public string zarplata { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string gorod { get; set; }
        public int educationID { get; set; }
        public int grafikID { get; set; }
        public int polID { get; set; }
        public int zanaytostID { get; set; }
        public string image { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual Grafik Grafik { get; set; }
        public virtual Pol Pol { get; set; }
        public virtual Zanaytost Zanaytost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRezume> UserRezume { get; set; }
    }
}
