//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndruhaBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRezume
    {
        public int id { get; set; }
        public int RezumeID { get; set; }
        public int userID { get; set; }
    
        public virtual Rezume Rezume { get; set; }
        public virtual User User { get; set; }
    }
}
